export const DIFFICULTIES = {
  NORMAL: 'Normal',
  CRUEL: 'Cruel',
  MERCILESS: 'Merciless',
  ETERNAL: 'Eternal',
};

export default [
  {
    id: 0,
    zone: 'The Prison',
    act: 1,
    location: 'lower level',
    difficulty: DIFFICULTIES.NORMAL,
  },
  {
    id: 1,
    zone: 'The Crypt',
    act: 2,
    location: 'level 1',
    difficulty: DIFFICULTIES.NORMAL,
  },
  {
    id: 2,
    zone: 'The Chamber of Sins',
    act: 2,
    location: 'level 2',
    difficulty: DIFFICULTIES.NORMAL,
  },
  {
    id: 3,
    zone: 'The Crematorium',
    act: 3,
    location: '',
    difficulty: DIFFICULTIES.NORMAL,
  },
  {
    id: 4,
    zone: 'The Catacombs',
    act: 3,
    location: '',
    difficulty: DIFFICULTIES.NORMAL,
  },
  {
    id: 5,
    zone: 'The Imperial Gardens',
    act: 3,
    location: '',
    difficulty: DIFFICULTIES.NORMAL,
  },
  {
    id: 6,
    zone: 'The Prison',
    act: 6,
    location: '',
    difficulty: DIFFICULTIES.CRUEL,
  },
  {
    id: 7,
    zone: 'The Crypt',
    act: 7,
    location: '',
    difficulty: DIFFICULTIES.CRUEL,
  },
  {
    id: 8,
    zone: 'The Chamber of Sins Level 2',
    act: 7,
    location: '',
    difficulty: DIFFICULTIES.CRUEL,
  },
  {
    id: 9,
    zone: 'The Bath House',
    act: 8,
    location: '',
    difficulty: DIFFICULTIES.MERCILESS,
  },
  {
    id: 10,
    zone: 'The Tunnel',
    act: 9,
    location: '',
    difficulty: DIFFICULTIES.MERCILESS,
  },
  {
    id: 11,
    zone: 'The Ossuary',
    act: 10,
    location: '',
    difficulty: DIFFICULTIES.MERCILESS,
  },
  {
    id: 12,
    zone: 'Trial of Piercing Truth',
    act: null,
    location: '',
    difficulty: DIFFICULTIES.ETERNAL,
  },
  {
    id: 13,
    zone: 'Trial of Swirling Fear',
    act: null,
    location: '',
    difficulty: DIFFICULTIES.ETERNAL,
  },
  {
    id: 14,
    zone: 'Trial of Crippling Grief',
    act: null,
    location: '',
    difficulty: DIFFICULTIES.ETERNAL,
  },
  {
    id: 15,
    zone: 'Trial of Burning Rage',
    act: null,
    location: '',
    difficulty: DIFFICULTIES.ETERNAL,
  },
  {
    id: 16,
    zone: 'Trial of Lingering Pain',
    act: null,
    location: '',
    difficulty: DIFFICULTIES.ETERNAL,
  },
  {
    id: 17,
    zone: 'Trial of Stinging Doubt',
    act: null,
    location: '',
    difficulty: DIFFICULTIES.ETERNAL,
  },
];
